<?xml version="1.0" encoding="UTF-8" ?> 
<xsd:schema
    targetNamespace="http://arireg.x-road.eu/producer/"
    elementFormDefault="qualified"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:swa="http://ws-i.org/profiles/basic/1.1/xsd"
    xmlns:sawsdl="http://www.w3.org/ns/sawsdl"
    xmlns:xrd="http://x-road.eu/xsd/xroad.xsd"
    xmlns:ar="http://arireg.x-road.eu/producer/">

    <xsd:complexType name="paringliht_tasuta_vastus">
        <xsd:sequence>
            <xsd:element name="ettevotjad" type="ar:paringliht_tasuta_ettevotted">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Ettevõtjad</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="leitud_ettevotjate_arv" type="xsd:integer">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Leitud ettevõtjate arv</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="paringliht_tasuta_ettevotted">

        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="item" type="ar:paringliht_tasuta_ettevote">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Ettevõtja</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="paringliht_tasuta_ettevote">
        <xsd:sequence>
            <xsd:element name="evnimi" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Arinimi" type="xsd:string">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Ettevõtja ärinimi/nimi</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element minOccurs="0" name="kehtetud_nimed" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Arinimi" type="ar:paringliht_tasuta_kehtetudnimed">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Ettevõtja kehtetud ärinimed</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element minOccurs="0" name="ariregistri_kood" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Maakohtu_poolt_registreeritud_isik_ariregistrikood" type="xsd:string">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Äriregistri kood</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="paringliht_tasuta_paring">
        <xsd:sequence>
            <xsd:element name="ariregister_kasutajanimi" type="xsd:string" nillable="true" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Äriregistri kasutajanimi</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="ariregister_parool" type="xsd:string" nillable="true" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Äriregistri parool</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="ariregister_sessioon" type="xsd:string" nillable="true" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Äriregistri sessioon</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="ariregister_valjundi_formaat" type="xsd:string" nillable="true" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Äriregistri väljundi formaat - "json", "xml" (vaikimisi)</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element minOccurs="0" name="evnimi" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Arinimi" type="xsd:string">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Ettevõtja kehtiva ärinime/nime osa</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element minOccurs="0" name="ariregistri_kood" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Maakohtu_poolt_registreeritud_isik_ariregistrikood" type="xsd:integer">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Ettevõtja täpne registrikood</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element minOccurs="0" name="evarv" type="xsd:integer">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Päringu vastusesse toodavate ettevõtjate arv</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element minOccurs="0" name="keel" type="xsd:string">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Klassifikaatorite tõlgete keel</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="paringliht_tasuta_kehtetudnimed">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="evnimi" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Arinimi" type="ar:paringliht_tasuta_kehtetunimi">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Ettevõtja kehtetu ärinimi</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="paringliht_tasuta_kehtetunimi">
        <xsd:sequence>
            <xsd:element name="evnimi" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Arinimi" type="xsd:string">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Nimi</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="algus_kpv" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Kehtivus_alguse_kuupaev" type="xsd:date">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Kehtivuse algus</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="lopp_kpv" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Kehtivuse_loppkuupaev" type="xsd:date">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Kehtivuse lõpp</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="lihtandmedTasuta_v1">
        <xsd:sequence>
            <xsd:element name="keha" type="ar:paringliht_tasuta_paring" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="lihtandmedTasuta_v1Response">
        <xsd:sequence>
            <xsd:element name="paring" type="ar:paringliht_tasuta_paring" />
            <xsd:element name="keha" type="ar:paringliht_tasuta_vastus" />
        </xsd:sequence>
    </xsd:complexType>

<!-- wrapper declarations -->
    <xsd:element name="lihtandmedTasuta_v1" type="ar:lihtandmedTasuta_v1"/>
    <xsd:element name="lihtandmedTasuta_v1Response" type="ar:lihtandmedTasuta_v1Response"/>
<!-- /wrapper declarations -->

</xsd:schema>
