//! WSDL → DSL generation. Task 013.
//!
//! Ingests `<wsdl_watch_dir>/<group>/*.wsdl` at boot, parses the
//! SOAP-1.1-over-HTTP subset X-Road uses, emits one DSL YAML per
//! `wsdl:operation` into `<dsl_path>/<group>/<operation>.yml`.
//!
//! Non-goals per task 013 v5: no admin HTTP endpoint, no hot
//! reload (v2 follow-up), no WSDL 2.0, no RPC/encoded style,
//! no MIME attachments. Bail-out-on-unsupported-construct posture
//! — never emit a wrong DSL silently.

pub mod generator;
pub mod parser;
pub mod pipeline;
pub mod url_guard;

pub use pipeline::ingest_all;

/// Marker header line written at the top of every generated DSL.
/// The presence/absence of this line is what distinguishes
/// generator-owned files (safe to overwrite) from hand-written
/// overrides (must not touch).
pub const MARKER: &str = "# GENERATED BY XTR from WSDL — do not edit; delete this line to convert into a hand-written override";
