<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xrd="http://x-road.eu/xsd/xroad.xsd" xmlns:tns="http://www.maaamet.ee" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.maaamet.ee">
    <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:mis="http://www.maaamet.ee" targetNamespace="http://www.maaamet.ee" xmlns:xrd="http://x-road.eu/xsd/xroad.xsd">
  <import namespace="http://x-road.eu/xsd/xroad.xsd" schemaLocation="http://x-road.eu/xsd/xroad.xsd"/>

  <element name="featureClasses">
    <complexType>
      <sequence/>
    </complexType>
  </element>

  <element name="featureClassesResponse">
    <complexType>
      <sequence>
        <element name="featureClass" type="string" maxOccurs="unbounded">
          <annotation>
            <appinfo>
              <xrd:title xml:lang="et">ETAK nähtusklass</xrd:title>
            </appinfo>
          </annotation>
        </element>
      </sequence>
    </complexType>
  </element>

</schema>
      
</wsdl:types>
    <wsdl:message name="requestHeader">
        <wsdl:part name="client" element="xrd:client"/>
        <wsdl:part name="service" element="xrd:service"/>
        <wsdl:part name="id" element="xrd:id"/>
        <wsdl:part name="userId" element="xrd:userId"/>
        <wsdl:part name="issue" element="xrd:issue"/>
        <wsdl:part name="protocolVersion" element="xrd:protocolVersion"/>
    </wsdl:message>
    <wsdl:message name="featureClasses">
        <wsdl:part name="body" element="tns:featureClasses"/>
    </wsdl:message>
    <wsdl:message name="featureClassesResponse">
        <wsdl:part name="body" element="tns:featureClassesResponse"/>
    </wsdl:message>
    <wsdl:portType name="servicePortType">
        <wsdl:operation name="featureClasses">
          <wsdl:documentation>
            <xrd:title xml:lang="et">ETAK nähtusklassid </xrd:title>
          </wsdl:documentation>
          <wsdl:input message="tns:featureClasses"/>
            <wsdl:output message="tns:featureClassesResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="serviceBinding" type="tns:servicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="featureClasses">
            <soap:operation soapAction="" style="document"/>
            <xrd:version>v1</xrd:version>
            <wsdl:input>
                <soap:body use="literal"/>
                <soap:header message="tns:requestHeader" part="client" use="literal"/>
                <soap:header message="tns:requestHeader" part="service" use="literal"/>
                <soap:header message="tns:requestHeader" part="id" use="literal"/>
                <soap:header message="tns:requestHeader" part="userId" use="literal"/>
                <soap:header message="tns:requestHeader" part="issue" use="literal"/>
                <soap:header message="tns:requestHeader" part="protocolVersion" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
                <soap:header message="tns:requestHeader" part="client" use="literal"/>
                <soap:header message="tns:requestHeader" part="service" use="literal"/>
                <soap:header message="tns:requestHeader" part="id" use="literal"/>
                <soap:header message="tns:requestHeader" part="userId" use="literal"/>
                <soap:header message="tns:requestHeader" part="issue" use="literal"/>
                <soap:header message="tns:requestHeader" part="protocolVersion" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="xroadeuService">
        <wsdl:port binding="tns:serviceBinding" name="xroadeuServicePort">
            <soap:address location="http://example.org/xroad-endpoint"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>