<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xrd="http://x-road.eu/xsd/xroad.xsd" xmlns:tns="http://www.maaamet.ee" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.maaamet.ee">
    <wsdl:types>

<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ads="http://www.maaamet.ee" targetNamespace="http://www.maaamet.ee" xmlns:xrd="http://x-road.eu/xsd/xroad.xsd">
  <import namespace="http://x-road.eu/xsd/xroad.xsd" schemaLocation="https://x-road.eu/xsd/xroad.xsd"/>
  <include schemaLocation="https://www.maaamet.ee/schemas/xtee6/ads_types.xsd"/>
  <element name="ADSaadrmuudatusedV7">
    <complexType>
      <annotation>
        <appinfo>
          <xrd:title>Aadressi muudatuste päring (ADSaadrmuudatusedV7)</xrd:title>
        </appinfo>
      </annotation>
      <sequence>
        <element name="muudetudAlates" minOccurs="0" type="date">
          <annotation>
            <appinfo>
              <xrd:title>Muudetud alates</xrd:title>
              <xrd:notes>Kuupäev alates millest (k.a) registreeritud muudatusi soovitakse leida</xrd:notes>
            </appinfo>
          </annotation>
        </element>
        <element name="muudetudPaevad" minOccurs="0" default="1">
          <annotation>
            <appinfo>
              <xrd:title>Muudatuste päevade arv</xrd:title>
              <xrd:notes>Number vahemikus 1-10 ehk mitme päeva muudatusi vastusesse soovitakse. Vaikimisi 1 päev.</xrd:notes>
            </appinfo>
          </annotation>
          <simpleType>
            <restriction base="int">
              <minInclusive value="1"/>
              <maxInclusive value="10"/>
            </restriction>
          </simpleType>
        </element>
        <element name="logId" type="integer" minOccurs="0">
          <annotation>
            <appinfo>
              <xrd:title>Logikirje ID</xrd:title>
              <xrd:notes>LogId, mille väärtusest suuremaid kirjeid otsitakse</xrd:notes>
            </appinfo>
          </annotation>
        </element>
        <element name="maxarv" minOccurs="0">
          <annotation>
            <appinfo>
              <xrd:title>Tagastatav kirjete max arv</xrd:title>
            </appinfo>
          </annotation>
          <simpleType>
            <restriction base="integer">
              <maxInclusive value="100"/>
            </restriction>
          </simpleType>
        </element>
        <element name="pSyndmused" type="boolean" default="false" minOccurs="0">
          <annotation>
            <appinfo>
              <xrd:title>Tagasta ka aadressi esinduspunkti muudatuse sündmus</xrd:title>
              <xrd:notes>True - tagastab ka P sündmuse, False - P sündmusi ei arvestata</xrd:notes>
            </appinfo>
          </annotation>
        </element>
        <element name="sSyndmused" type="boolean" default="false" minOccurs="0">
          <annotation>
            <appinfo>
              <xrd:title>Tagasta ka seoste kadumise sündmus</xrd:title>
              <xrd:notes>True - tagastab ka S sündmuse, False - S sündmusi ei arvestata</xrd:notes>
            </appinfo>
          </annotation>
        </element>
        <element name="nSyndmused" type="boolean" default="false" minOccurs="0">
          <annotation>
            <appinfo>
              <xrd:title>Tagasta ka sihtnumbri muudatuse sündmus</xrd:title>
              <xrd:notes>True - tagastab ka N sündmuse, False - N sündmusi ei arvestata</xrd:notes>
            </appinfo>
          </annotation>
        </element>
        <element name="aSyndmused" type="boolean" default="false" minOccurs="0">
          <annotation>
            <appinfo>
              <xrd:title>Tagasta ka mitteametliku piirkonna nime muudatuse sündmus</xrd:title>
              <xrd:notes>True - tagastab ka A sündmuse, False - A sündmusi ei arvestata</xrd:notes>
            </appinfo>
          </annotation>
        </element>
        <element name="oSyndmused" type="boolean" default="false" minOccurs="0">
          <annotation>
            <appinfo>
              <xrd:title>Tagasta ka primaarseima objekti viida tekkimise või muutumise sündmus</xrd:title>
              <xrd:notes>True – tagastab ka O sündmuse, False – O sündmusi ei arvesta</xrd:notes>
            </appinfo>
          </annotation>
        </element>
        <element name="tSyndmused" type="boolean" default="false" minOccurs="0">
          <annotation>
            <appinfo>
              <xrd:title>Tagasta ka aadressile tunnuse „tehniline“ omistamisel / eemaldamisel tekkiv sündmus</xrd:title>
              <xrd:notes>True – tagastab ka T sündmuse, False – T sündmusi ei arvesta</xrd:notes>
            </appinfo>
          </annotation>
        </element>
        <element name="objekt" type="boolean" minOccurs="0" default="false">
          <annotation>
            <appinfo>
              <xrd:title>Tagasta ka muudatuse põhjustanud objekt</xrd:title>
              <xrd:notes>Kas tagastatakse ka muudatuse põhjustanud aadressiobjekti andmed.</xrd:notes>
            </appinfo>
          </annotation>
        </element>
        <element name="seosed" type="boolean" minOccurs="0" default="false">
          <annotation>
            <appinfo>
              <xrd:title>Tagasta ka aadressiga seotud objektid</xrd:title>
              <xrd:notes>Kas tagastatakse ka päringu hetkel aadressiga seotud kehtivas ja ootel olekus objektid.</xrd:notes>
            </appinfo>
          </annotation>
        </element>
        <element name="aadressKomp" type="boolean" minOccurs="0" default="false">
          <annotation>
            <appinfo>
              <xrd:title>Tagasta aadress komponentidena</xrd:title>
            </appinfo>
          </annotation>
        </element>
        <element name="aadressJarglased" type="boolean" minOccurs="0" default="false">
          <annotation>
            <appinfo>
              <xrd:title>Tagasta aadressi eellased/järglased</xrd:title>
            </appinfo>
          </annotation>
        </element>
        <element name="liidestujaObjektid" type="boolean" minOccurs="0" default="false">
          <annotation>
            <appinfo>
              <xrd:title>Tagasta objektiga seotud Kinnistusraamatu korteriomandid ja Äriregistri juriidilised isikud</xrd:title>
            </appinfo>
          </annotation>
        </element>
      </sequence>
    </complexType>
  </element>
  <element name="ADSaadrmuudatusedV7Response">
    <complexType>
      <sequence>
      <element name="muudatused" minOccurs="0">
        <complexType>
          <sequence>
            <element name="muudatus" maxOccurs="unbounded">
          <complexType>
            <sequence>
              <element name="logId" type="integer">
                <annotation>
                  <appinfo>
                    <xrd:title>Logikirje ID</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="logStamp" type="dateTime">
                <annotation>
                  <appinfo>
                    <xrd:title>Logikirje tekkimise aeg</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="syndmus" type="ads:aadrSyndmusType">
                <annotation>
                  <appinfo>
                    <xrd:title>Sündmus</xrd:title>
                    <xrd:notes>I(insert) – aadress lisati süsteemi, U(update) – samade komponentidega aadressi tekst muutus, aadress versiooniti, D(delete) – aadress tühistati, R(restore) – aadress taastati
                      P – esinduspunkti koordinaate muudeti, S – aadressi kõik seosed kadusid, N – sihtnumber muutus, A – mitteametlik piirkond muutus, O – aadressi primaarobjekt muutus, T – lisati/eemaldati tunnus, et aadress on tehniline</xrd:notes>
                  </appinfo>
                </annotation>
              </element>
              <element name="koodAadress" type="string">
                <annotation>
                  <appinfo>
                    <xrd:title>Koodaadress</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="adrId" type="integer">
                <annotation>
                  <appinfo>
                    <xrd:title>Aadressi versiooni ID (ADR_ID)</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="taisAadress" type="string">
                <annotation>
                  <appinfo>
                    <xrd:title>Täisaadress</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="lahiAadress" type="string" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Lähiaadress</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="sihtnumber" type="integer" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Sihtnumber (postiindeks)</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="maPiirkond" type="string" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Mitteametlike piirkondade nimed, millesse aadress kuulub</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="maPiirkondAlias" type="string" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Mitteametlike piirkondade sünonüümid ehk alternatiivsed nimevariandid</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="tehniline" type="boolean" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Tunnus, kas tegemist on tehnilise aadressiga</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="primaarseimObjekt" type="string" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>ADR_ID-ga seotud primaarseima objekt ADS_OID</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="vanaAdrId" type="integer" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Aadressi eelmise versiooni ID (ADR_ID) muutmise korral</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="vanaTaisAadress" type="string" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Aadressi eelmise versiooni täisaadress</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="vanaLahiAadress" type="string" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Aadressi eelmise versiooni lähiaadress</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="esindusPunktX" type="double" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Aadressi esinduspunkti x-koordinaat L-Est süsteemis</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="esindusPunktY" type="double" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Aadressi esinduspunkti y-koordinaat L-Est süsteemis</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="eellased" type="string" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Aadressi eellased</xrd:title>
                    <xrd:notes>Aadressi võimalikeks eellasteks olevate tühistatud aadresside ADR_ID väärtuste loetelu või aadressi vananenud versiooni ADR_ID. Eellased antakse ainult kehtivate aadresside korral. Eellased järjestatakse kehtetuks muutumise aja järgi kahanevalt. Loetelu eraldatud semikoolonitega.</xrd:notes>
                  </appinfo>
                </annotation>
              </element>
              <element name="jarglased" type="string" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Aadressi järglased</xrd:title>
                    <xrd:notes>Aadressi võimalikeks järglasteks olevate kehtivate aadresside ADR_ID väärtuste loetelu. Loetelu eraldatud semikoolonitega. Järglased on võimalikud tühistatud (olek = T) ja vananenud aadressi (olek=V) korral. Järglased järjestatakse kehtivuse alguse aja järgi kasvavalt.</xrd:notes>
                  </appinfo>
                </annotation>
              </element>
              <element name="poleSeotud" type="boolean">
                <annotation>
                  <appinfo>
                    <xrd:title>Aadress on kehtetu ja ta pole seotud ühegi kehtiva objektiga</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="kehtiv" type="dateTime" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Aadressi versiooni kehtivuse alguse kuupäev ja kellaaeg</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="kehtetu" type="dateTime" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Aadressi versiooni kehtivuse lõpu kuupäev ja kellaaeg</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="objektiLiik" type="ads:adsobjliikKlassifikaator" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Muudatuse põhjustanud objekti liik</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="adsOid" type="string" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Muudatuse põhjustanud objekti identifikaator ADS süsteemis (ADS_OID)</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="adobId" type="string" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Muudatuse põhjustanud objekti versiooni ID ADS süsteemis (ADOB_ID)</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="origTunnus" type="string" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Muudatuse põhjustanud objekti tunnus päritoluregistris</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="objektiPunktX" type="double" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Muudatuse põhjustanud objekti viitepunkti x-koordinaat L-Est süsteemis</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="objektiPunktY" type="double" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Muudatuse põhjustanud objekti viitepunkti x-koordinaat L-Est süsteemis</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="etakId" type="integer" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Muudatuse põhjustanud hoone tunnus ETAK süsteemis (ETAK_ID)</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="olek" type="ads:objOlekType" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Muudatuse põhjustanud objekti olek</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="aadressiPunktX" type="double" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Muudatuse põhjustanud objekti aadressipunkti x-koordinaat L-Est süsteemis</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="aadressiPunktY" type="double" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Muudatuse põhjustanud objekti aadressipunkti y-koordinaat L-Est süsteemis</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="liidestujaObjektid" minOccurs="0">
                <complexType>
                  <sequence>
                    <element name="liidestujaObjekt" maxOccurs="unbounded">
                      <complexType>
                        <sequence>
                          <element name="register" type="ads:adsRegisterType" minOccurs="0">
                            <annotation>
                              <appinfo>
                                <xrd:title>Register</xrd:title>
                              </appinfo>
                            </annotation>
                          </element>
                          <element name="idRegistris" type="string" minOccurs="0">
                            <annotation>
                              <appinfo>
                                <xrd:title>Objekti tunnus liidestunud registris</xrd:title>
                                <xrd:notes>Vastavalt kas korteriomandi number või äriregistri registrikood</xrd:notes>
                              </appinfo>
                            </annotation>
                          </element>
                          <element name="lisainfo" type="string" minOccurs="0">
                            <annotation>
                              <appinfo>
                                <xrd:title>Eriomandi number korteriomandi puhul või juriidilise isiku nimi</xrd:title>
                              </appinfo>
                            </annotation>
                          </element>
                        </sequence>
                      </complexType>
                    </element>
                  </sequence>
                </complexType>
              </element>
              <element name="adrSeosed" minOccurs="0">
                <complexType>
                  <sequence>
                    <element name="adrSeos" minOccurs="0" maxOccurs="unbounded">
                      <complexType>
                        <sequence>
                          <element name="objektiLiik" type="ads:adsobjliikKlassifikaator">
                            <annotation>
                              <appinfo>
                                <xrd:title>Aadressiga seotud objekti liik</xrd:title>
                              </appinfo>
                            </annotation>
                          </element>
                          <element name="adsOid" type="string">
                            <annotation>
                              <appinfo>
                                <xrd:title>Aadressiga seotud objekti identifikaator ADS süsteemis (ADS_OID)</xrd:title>
                              </appinfo>
                            </annotation>
                          </element>
                          <element name="adobId" type="string">
                            <annotation>
                              <appinfo>
                                <xrd:title>Aadressiga seotud objekti versiooni ID ADS süsteemis (ADOB_ID)</xrd:title>
                              </appinfo>
                            </annotation>
                          </element>
                          <element name="origTunnus" type="string" minOccurs="0">
                            <annotation>
                              <appinfo>
                                <xrd:title>Aadressiga seotud objekti tunnus päritoluregistris</xrd:title>
                              </appinfo>
                            </annotation>
                          </element>
                          <element name="unikaalne" type="boolean" minOccurs="0">
                            <annotation>
                              <appinfo>
                                <xrd:title>Aadressiga seotud objekti UN-tunnus</xrd:title>
                              </appinfo>
                            </annotation>
                          </element>
                          <element name="etakId" type="integer" minOccurs="0">
                            <annotation>
                              <appinfo>
                                <xrd:title>Aadressiga seotud hoone tunnus ETAK süsteemis (ETAK_ID)</xrd:title>
                              </appinfo>
                            </annotation>
                          </element>
                          <element name="olek" type="ads:objOlekType" minOccurs="0">
                            <annotation>
                              <appinfo>
                                <xrd:title>Aadressiga seotud objekti olek</xrd:title>
                              </appinfo>
                            </annotation>
                          </element>
                          <element name="aadressiPunktX" type="double" minOccurs="0">
                            <annotation>
                              <appinfo>
                                <xrd:title>Aadressiga seotud objekti aadressipunkti x-koordinaat L-Est süsteemis</xrd:title>
                              </appinfo>
                            </annotation>
                          </element>
                          <element name="aadressiPunktY" type="double" minOccurs="0">
                            <annotation>
                              <appinfo>
                                <xrd:title>Aadressiga seotud objekti aadressipunkti y-koordinaat L-Est süsteemis</xrd:title>
                              </appinfo>
                            </annotation>
                          </element>
                          <element name="liidestujaObjektid" minOccurs="0">
                            <complexType>
                              <sequence>
                                <element name="liidestujaObjekt" maxOccurs="unbounded">
                                  <complexType>
                                    <sequence>
                                      <element name="register" type="ads:adsRegisterType" minOccurs="0">
                                        <annotation>
                                          <appinfo>
                                            <xrd:title>Register</xrd:title>
                                          </appinfo>
                                        </annotation>
                                      </element>
                                      <element name="idRegistris" type="string" minOccurs="0">
                                        <annotation>
                                          <appinfo>
                                            <xrd:title>Objekti tunnus liidestunud registris</xrd:title>
                                            <xrd:notes>Vastavalt kas korteriomandi number või äriregistri registrikood</xrd:notes>
                                          </appinfo>
                                        </annotation>
                                      </element>
                                      <element name="lisainfo" type="string" minOccurs="0">
                                        <annotation>
                                          <appinfo>
                                            <xrd:title>Eriomandi number korteriomandi puhul või juriidilise isiku nimi</xrd:title>
                                          </appinfo>
                                        </annotation>
                                      </element>
                                    </sequence>
                                  </complexType>
                                </element>
                              </sequence>
                            </complexType>
                          </element>
                        </sequence>
                      </complexType>
                    </element>
                  </sequence>
                </complexType>
              </element>
              <element name="adsTase1" type="ads:adsTaseType" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Tase 1</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="adsTase2" type="ads:adsTaseType" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Tase 2</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="adsTase3" type="ads:adsTaseType" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Tase 3</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="adsTase4" type="ads:adsTaseType" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Tase 4</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="adsTase5" type="ads:adsTaseType" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Tase 5</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="adsTase6" type="ads:adsTaseType" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Tase 6</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="adsTase7" type="ads:adsTaseType" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Tase 7</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="adsTase8" type="ads:adsTaseType" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Tase 8</xrd:title>
                  </appinfo>
                </annotation>
              </element>
              <element name="muudetudTase" type="integer" minOccurs="0">
                <annotation>
                  <appinfo>
                    <xrd:title>Taseme number, mis põhjustas aadressi muudatuse või tühistamise (U ja D sündmuse korral)</xrd:title>
                  </appinfo>
                </annotation>
              </element>
            </sequence>
          </complexType>
        </element>
      </sequence>
      </complexType>
      </element>
      <element name="fault" minOccurs="0">
        <complexType>
          <sequence>
            <element name="faultCode" type="string">
              <annotation>
                <appinfo>
                  <xrd:title>Vea kood</xrd:title>
                </appinfo>
              </annotation>
            </element>
            <element name="faultString" type="string">
              <annotation>
                <appinfo>
                  <xrd:title>Vea kirjeldus</xrd:title>
                </appinfo>
              </annotation>
            </element>
          </sequence>
        </complexType>
      </element>
      </sequence>
    </complexType>
  </element>
  <simpleType name="aadrSyndmusType">
    <restriction base="string">
      <enumeration value="I">
        <annotation>
          <appinfo>
            <xrd:title>lisamine</xrd:title>
          </appinfo>
        </annotation>
      </enumeration>
      <enumeration value="U">
        <annotation>
          <appinfo>
            <xrd:title>muutmine</xrd:title>
          </appinfo>
        </annotation>
      </enumeration>
      <enumeration value="D">
        <annotation>
          <appinfo>
            <xrd:title>tühistamine</xrd:title>
          </appinfo>
        </annotation>
      </enumeration>
      <enumeration value="R">
        <annotation>
          <appinfo>
            <xrd:title>taastamine</xrd:title>
          </appinfo>
        </annotation>
      </enumeration>
      <enumeration value="P">
        <annotation>
          <appinfo>
            <xrd:title>punkti muudatus</xrd:title>
          </appinfo>
        </annotation>
      </enumeration>
      <enumeration value="S">
        <annotation>
          <appinfo>
            <xrd:title>seoste kadumine</xrd:title>
          </appinfo>
        </annotation>
      </enumeration>
      <enumeration value="N">
        <annotation>
          <appinfo>
            <xrd:title>sihtnumbri muudatus</xrd:title>
          </appinfo>
        </annotation>
      </enumeration>
      <enumeration value="A">
        <annotation>
          <appinfo>
            <xrd:title>mitteametliku piirkonna nime muudatus</xrd:title>
          </appinfo>
        </annotation>
      </enumeration>
      <enumeration value="O">
        <annotation>
          <appinfo>
            <xrd:title>prioriteetseima objekti muudatus</xrd:title>
          </appinfo>
        </annotation>
      </enumeration>
      <enumeration value="T">
        <annotation>
          <appinfo>
            <xrd:title>tehnilise tunnuse muudatus</xrd:title>
          </appinfo>
        </annotation>
      </enumeration>
    </restriction>
  </simpleType>
  <simpleType name="objOlekType">
    <restriction base="string">
      <enumeration value="K">
        <annotation>
          <appinfo>
            <xrd:title>kehtiv</xrd:title>
          </appinfo>
        </annotation>
      </enumeration>
      <enumeration value="O">
        <annotation>
          <appinfo>
            <xrd:title>ootel</xrd:title>
          </appinfo>
        </annotation>
      </enumeration>
    </restriction>
  </simpleType>
</schema>
</wsdl:types>
    <wsdl:message name="requestHeader">
        <wsdl:part name="client" element="xrd:client"/>
        <wsdl:part name="service" element="xrd:service"/>
        <wsdl:part name="id" element="xrd:id"/>
        <wsdl:part name="userId" element="xrd:userId"/>
        <wsdl:part name="issue" element="xrd:issue"/>
        <wsdl:part name="protocolVersion" element="xrd:protocolVersion"/>
    </wsdl:message>
    <wsdl:message name="ADSaadrmuudatusedV7">
        <wsdl:part name="body" element="tns:ADSaadrmuudatusedV7"/>
    </wsdl:message>
    <wsdl:message name="ADSaadrmuudatusedV7Response">
        <wsdl:part name="body" element="tns:ADSaadrmuudatusedV7Response"/>
    </wsdl:message>
    <wsdl:portType name="servicePortType">
        <wsdl:operation name="ADSaadrmuudatusedV7">
          <wsdl:documentation>
            <xrd:title xml:lang="et">Aadressi muudatuste päring</xrd:title>
          </wsdl:documentation>
          <wsdl:input message="tns:ADSaadrmuudatusedV7"/>
            <wsdl:output message="tns:ADSaadrmuudatusedV7Response"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="serviceBinding" type="tns:servicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="ADSaadrmuudatusedV7">
            <soap:operation soapAction="" style="document"/>
            <xrd:version>v1</xrd:version>
            <wsdl:input>
                <soap:body use="literal"/>
                <soap:header message="tns:requestHeader" part="client" use="literal"/>
                <soap:header message="tns:requestHeader" part="service" use="literal"/>
                <soap:header message="tns:requestHeader" part="id" use="literal"/>
                <soap:header message="tns:requestHeader" part="userId" use="literal"/>
                <soap:header message="tns:requestHeader" part="issue" use="literal"/>
                <soap:header message="tns:requestHeader" part="protocolVersion" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
                <soap:header message="tns:requestHeader" part="client" use="literal"/>
                <soap:header message="tns:requestHeader" part="service" use="literal"/>
                <soap:header message="tns:requestHeader" part="id" use="literal"/>
                <soap:header message="tns:requestHeader" part="userId" use="literal"/>
                <soap:header message="tns:requestHeader" part="issue" use="literal"/>
                <soap:header message="tns:requestHeader" part="protocolVersion" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="xroadeuService">
        <wsdl:port binding="tns:serviceBinding" name="xroadeuServicePort">
            <soap:address location="http://example.org/xroad-endpoint"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>