<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:sch="http://ehr.ee.x-road.eu/producer/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ehrdev.x-road.eu" xmlns:xrd="http://x-road.eu/xsd/xroad.xsd" targetNamespace="http://ehrdev.x-road.eu">
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ehr="http://ehr.ee.x-road.eu/producer/" xmlns:tns="http://ehr.ee.x-road.eu/producer/" xmlns:xrd="http://x-road.eu/xsd/x-road.xsd" targetNamespace="http://ehr.ee.x-road.eu/producer/">
            <import namespace="http://x-road.eu/xsd/xroad.xsd" schemaLocation="http://x-road.eu/xsd/xroad.xsd"/>
            <include schemaLocation="https://devkluster.ehr.ee/api/xtee/v1/services/ehr_xrd.xsd"/>
            <element name="ehrIsikuteParing">
                <complexType>
                    <sequence>
                        <element name="request" type="tns:ehrIsikuteParingRequestType"/>
                    </sequence>
                </complexType>
            </element>
            <complexType name="ehrIsikuteParingRequestType">
                <sequence>
                    <element name="isikuliik" type="string">
                        <annotation>
                            <appinfo>
                                <xrd:title>Isikuliik</xrd:title>
                            </appinfo>
                        </annotation>
                    </element>
                    <element minOccurs="0" name="isikukood" type="string">
                        <annotation>
                            <appinfo>
                                <xrd:title>Isikukood</xrd:title>
                            </appinfo>
                        </annotation>
                    </element>
                    <element minOccurs="0" name="perekonnanimi" type="string">
                        <annotation>
                            <appinfo>
                                <xrd:title>Perekonnanimi</xrd:title>
                            </appinfo>
                        </annotation>
                    </element>
                    <element minOccurs="0" name="eesnimi" type="string">
                        <annotation>
                            <appinfo>
                                <xrd:title>Eesnimi</xrd:title>
                            </appinfo>
                        </annotation>
                    </element>
                    <element minOccurs="0" name="synniaeg" type="date">
                        <annotation>
                            <appinfo>
                                <xrd:title>Sünniaeg</xrd:title>
                            </appinfo>
                        </annotation>
                    </element>
                    <element minOccurs="0" name="endised" type="string">
                        <annotation>
                            <appinfo>
                                <xrd:title>Endised</xrd:title>
                                <xrd:notes>Staatuskood</xrd:notes>
                            </appinfo>
                        </annotation>
                    </element>
                </sequence>
            </complexType>
            <element name="ehrIsikuteParingResponse">
                <complexType>
                    <sequence>
                        <element name="request" type="tns:ehrIsikuteParingRequestType"/>
                        <element name="response" type="ehr:ehrIsikuteParingResponseType"/>
                    </sequence>
                </complexType>
            </element>
        </schema>
    </wsdl:types>
    <wsdl:message name="ehrIsikuteParingResponse">
        <wsdl:part element="sch:ehrIsikuteParingResponse" name="ehrIsikuteParingResponse"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="ehrIsikuteParing">
        <wsdl:part element="sch:ehrIsikuteParing" name="ehrIsikuteParing"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="requestheader">
        <wsdl:part element="xrd:client" name="client"> </wsdl:part>
        <wsdl:part element="xrd:service" name="service"> </wsdl:part>
        <wsdl:part element="xrd:id" name="id"> </wsdl:part>
        <wsdl:part element="xrd:userId" name="userId"> </wsdl:part>
        <wsdl:part element="xrd:protocolVersion" name="protocolVersion"> </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="ehrPort">
        <wsdl:operation name="ehrIsikuteParing">
            <wsdl:documentation>
                <xrd:title>EHR registri isikute päring</xrd:title>
            </wsdl:documentation>
            <wsdl:input message="tns:ehrIsikuteParing" name="ehrIsikuteParing"> </wsdl:input>
            <wsdl:output message="tns:ehrIsikuteParingResponse" name="ehrIsikuteParingResponse"> </wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ehrPortSoap11" type="tns:ehrPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="ehrIsikuteParing">
            <soap:operation soapAction=""/>
            <xrd:version>v1</xrd:version>
            <wsdl:input name="ehrIsikuteParing">
                <soap:header message="tns:requestheader" part="client" use="literal"> </soap:header>
                <soap:header message="tns:requestheader" part="service" use="literal"> </soap:header>
                <soap:header message="tns:requestheader" part="userId" use="literal"> </soap:header>
                <soap:header message="tns:requestheader" part="id" use="literal"> </soap:header>
                <soap:header message="tns:requestheader" part="protocolVersion" use="literal"> </soap:header>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="ehrIsikuteParingResponse">
                <soap:header message="tns:requestheader" part="client" use="literal"> </soap:header>
                <soap:header message="tns:requestheader" part="service" use="literal"> </soap:header>
                <soap:header message="tns:requestheader" part="userId" use="literal"> </soap:header>
                <soap:header message="tns:requestheader" part="id" use="literal"> </soap:header>
                <soap:header message="tns:requestheader" part="protocolVersion" use="literal"> </soap:header>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ehrService">
        <wsdl:port binding="tns:ehrPortSoap11" name="ehrPortSoap11">
            <soap:address location="http://example.org/xroad-endpoint"/>
            <xrd:address producer="ehrdev"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>