<?xml version="1.0" encoding="UTF-8" ?> 
<xsd:schema
    targetNamespace="http://arireg.x-road.eu/producer/"
    elementFormDefault="qualified"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:swa="http://ws-i.org/profiles/basic/1.1/xsd"
    xmlns:sawsdl="http://www.w3.org/ns/sawsdl"
    xmlns:xrd="http://x-road.eu/xsd/xroad.xsd"
    xmlns:ar="http://arireg.x-road.eu/producer/">

    <xsd:complexType name="aruande_auditeerimiseandmed_vastus">
        <xsd:sequence>
            <xsd:element name="kirjed" type="ar:aruande_auditeerimiseandmed_kirjed">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Kirjed</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="leitud_kirjete_arv" type="xsd:integer">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Leitud kirjete arv</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="aruande_auditeerimiseandmed_kirjed">
        <xsd:sequence>
            <xsd:element name="item" type="ar:aruande_auditeerimiseandmed_kirje" maxOccurs="unbounded" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Kirje</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="aruande_auditeerimiseandmed_kirje">
        <xsd:sequence>
            <xsd:element name="ariregistri_kood" type="xsd:string" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Maakohtu_poolt_registreeritud_isik_ariregistrikood">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Äriregistri kood</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="esitamise_aeg" type="xsd:dateTime">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Esitamise aeg</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="aasta" type="xsd:integer" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Aruande_aasta">
                <xsd:annotation>
                    <xsd:documentation>Aruande aasta</xsd:documentation>
                    <xsd:appinfo>
                        <xrd:title>Aruande aasta</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="aruande_aasta_algus" type="xsd:date">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Aruandeaasta algus</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="aruande_aasta_lopp" type="xsd:date">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Aruandeaasta lõpp</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="kohustuslik_audit" type="xsd:boolean" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Kas oli kohustuslik või vabatahtlik auditeerimine</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="audiitorid" type="ar:aruande_auditeerimiseandmed_kirje_audiitorid">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Müügitulu kirjed</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="aruande_auditeerimiseandmed_kirje_audiitorid">
        <xsd:sequence>
            <xsd:element name="item" type="ar:aruande_auditeerimiseandmed_kirje_audiitor" maxOccurs="unbounded" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Kirje</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="aruande_auditeerimiseandmed_kirje_audiitor">
        <xsd:sequence>
            <xsd:element name="va_kood" type="xsd:string">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Vandeaudiitori isikukood</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="va_nimi" type="xsd:string">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Vandeaudiitori nimi</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="va_kutsetunnistuse_nr" type="xsd:string">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Vandeaudiitori kutsetunnistuse number</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="aev_kood" type="xsd:string">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Audiitorettevõtja isikukood</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="aev_nimi" type="xsd:string">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Audiitorettevõtja nimi</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="aev_loa_nr" type="xsd:string">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Audiitorettevõtja tegevusloa number</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="audit_kpv" type="xsd:date">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Auditeerimise/allkirjastamise kuupäev</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="aruande_auditeerimiseandmed_paring">
        <xsd:sequence>
            <xsd:element name="ariregister_kasutajanimi" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Äriregistri kasutajanimi</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="ariregister_parool" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Äriregistri parool</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="esitatud_algus" type="xsd:dateTime">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Esitatud aruannete vahemik kella aja täpsusega vahemik</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="esitatud_lopp" type="xsd:dateTime">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Esitatud aruannete vahemik kella aja täpsusega vahemik</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="ariregistri_kood" type="xsd:integer" minOccurs="0" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Maakohtu_poolt_registreeritud_isik_ariregistrikood">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Ettevõtja täpne registrikood</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="aruande_aasta" type="xsd:integer" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Aruande aasta</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="aev_ariregistri_kood" type="xsd:integer" minOccurs="0" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Maakohtu_poolt_registreeritud_isik_ariregistrikood">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>AEV täpne registrikood</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="lehekylg" type="xsd:integer" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Päringu vastuse lehekülg, vaikimisi 1 (1000 aruandekirjet per lehekülg)</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="keel" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Klassifikaatorite tõlgete keel</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="aruandeAuditeerimiseAndmed_v1">
        <xsd:sequence>
            <xsd:element name="keha" type="ar:aruande_auditeerimiseandmed_paring" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="aruandeAuditeerimiseAndmed_v1Response">
        <xsd:sequence>
            <xsd:element name="paring" type="ar:aruande_auditeerimiseandmed_paring" />
            <xsd:element name="keha" type="ar:aruande_auditeerimiseandmed_vastus" />
        </xsd:sequence>
    </xsd:complexType>

<!-- wrapper declarations -->
    <xsd:element name="aruandeAuditeerimiseAndmed_v1" type="ar:aruandeAuditeerimiseAndmed_v1"/>
    <xsd:element name="aruandeAuditeerimiseAndmed_v1Response" type="ar:aruandeAuditeerimiseAndmed_v1Response"/>
<!-- /wrapper declarations -->

</xsd:schema>
