<?xml version="1.0" encoding="UTF-8" ?> 
<xsd:schema
    targetNamespace="http://arireg.x-road.eu/producer/"
    elementFormDefault="qualified"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:swa="http://ws-i.org/profiles/basic/1.1/xsd"
    xmlns:sawsdl="http://www.w3.org/ns/sawsdl"
    xmlns:xrd="http://x-road.eu/xsd/xroad.xsd"
    xmlns:ar="http://arireg.x-road.eu/producer/">

    <xsd:complexType name="majandusaasta_aruannete_loetelu_paring">
        <xsd:sequence>

            <xsd:element name="ariregister_kasutajanimi" type="xsd:string" nillable="true" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Äriregistri kasutajanimi</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>

            <xsd:element name="ariregister_parool" type="xsd:string" nillable="true" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Äriregistri parool</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>

            <xsd:element name="ariregistri_kood" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Maakohtu_poolt_registreeritud_isik_ariregistrikood" type="xsd:int">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Äriregistri kood</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>

        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="majandusaasta_aruannete_loetelu_vastus">
        <xsd:sequence>

            <xsd:element minOccurs="0" maxOccurs="unbounded" name="majandusaasta_aruanded" type="ar:majandusaasta_aruanne">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Majandusaasta aruanne</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>

        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="majandusaasta_aruanne">
        <xsd:sequence>

            <xsd:element minOccurs="0" name="aruande_kood" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Aruande_kood" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Aruande kood</xsd:documentation>
                    <xsd:appinfo>
                        <xrd:title>Aruande kood</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>

            <xsd:element minOccurs="0" name="aruande_nimetus" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Aruande_nimetus" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Aruande nimetus</xsd:documentation>
                    <xsd:appinfo>
                        <xrd:title>Aruande nimetus</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>

            <xsd:element minOccurs="0" name="aruande_aasta" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Aruande_aasta" type="xsd:int">
                <xsd:annotation>
                    <xsd:documentation>Aruande aasta</xsd:documentation>
                    <xsd:appinfo>
                        <xrd:title>Aruande aasta</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>

            <xsd:element minOccurs="0" name="majandusaasta_algus" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Majandusaasta_algus" type="xsd:date">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Majandusaasta Algus</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>

            <xsd:element minOccurs="0" name="majandusaasta_lopp" sawsdl:modelReference="https://riha.eesti.ee/riha/onto/ettevotlus.ariregister/2010/r2#Majandusaasta_lopp" type="xsd:date">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Majandusaasta Lõpp</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>

        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="majandusaastaAruanneteLoetelu_v1">
        <xsd:sequence>
            <xsd:element name="keha" type="ar:majandusaasta_aruannete_loetelu_paring" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="majandusaastaAruanneteLoetelu_v1Response">
        <xsd:sequence>
            <xsd:element name="paring" type="ar:majandusaasta_aruannete_loetelu_paring" />
            <xsd:element name="keha" type="ar:majandusaasta_aruannete_loetelu_vastus" />
        </xsd:sequence>
    </xsd:complexType>

<!-- wrapper declarations -->
    <xsd:element name="majandusaastaAruanneteLoetelu_v1" type="ar:majandusaastaAruanneteLoetelu_v1"/>
    <xsd:element name="majandusaastaAruanneteLoetelu_v1Response" type="ar:majandusaastaAruanneteLoetelu_v1Response"/>
<!-- /wrapper declarations -->

</xsd:schema>
