<?xml version="1.0" encoding="UTF-8" ?> 
<xsd:schema
    targetNamespace="http://arireg.x-road.eu/producer/"
    elementFormDefault="qualified"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:swa="http://ws-i.org/profiles/basic/1.1/xsd"
    xmlns:sawsdl="http://www.w3.org/ns/sawsdl"
    xmlns:xrd="http://x-road.eu/xsd/xroad.xsd"
    xmlns:ar="http://arireg.x-road.eu/producer/">

    <xsd:complexType name="usaldushaldused_v1_Query">
        <xsd:sequence>
            <xsd:element name="ariregister_kasutajanimi" type="xsd:string" nillable="true" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Äriregistri kasutajanimi</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="ariregister_parool" type="xsd:string" nillable="true" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Äriregistri parool</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="ariregister_sessioon" type="xsd:string" nillable="true" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Äriregistri sessioon</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="ariregister_valjundi_formaat" type="xsd:string" nillable="true" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Äriregistri väljundi formaat - "json", "xml" (vaikimisi)</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="usaldushalduse_nimi" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Usaldushalduse nimi</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="fyysilise_isiku_eesnimi" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Seotud füüsilise isiku eesnimi</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="fyysilise_isiku_perekonnanimi" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Seotud füüsilise isiku perekonnanimi</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="fyysilise_isiku_synniaeg" type="xsd:date" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Seotud füüsilise isiku sünniaeg</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="fyysilise_isiku_kood" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Seotud füüsilise isiku isikukood</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="paringuPohjendus" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Tegeliku kasusaajate päringu põhjendus</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="seosEttevottega" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Päringu teostaja seos kasusaaja ettevõttega</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="paringuTegija" type="ar:paringuTegija" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Tegelike kasusaajate päringu õiguse kontrollimiseks</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="ainult_kehtivad" type="xsd:boolean" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Kas kuvada väljundisse ainult kehtivad andmed</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="keel" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Klassifikaatorite tõlgete keel (est-eesti, eng-inglise)</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="evarv" type="xsd:integer" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Usaldushalduste arv ühel leheküljel - kuni 100, vaikimisi 10</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element minOccurs="0" name="lehekylg" type="xsd:integer">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Tulemuse lehekülg, vaikimisi 1</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="usaldushaldused_v1_Vastus">
        <xsd:sequence>
            <xsd:element name="usaldushaldused" type="ar:usaldushaldused_v1_usaldushaldused" nillable="true" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Usaldushaldused</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="leitud_arv" type="xsd:integer">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Leitud Usaldushalduste arv</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="usaldushaldused_v1_usaldushaldused">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="item" type="ar:usaldushaldused_v1_usaldushaldus">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Usaldushaldus</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="usaldushaldused_v1_usaldushaldus">
        <xsd:sequence>
            <xsd:element name="usaldushalduse_id" type="xsd:integer">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Usaldushalduse sisemine ID</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="nimi" type="xsd:string">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Usaldushalduse nimetus</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="registreerimise_kpv" type="xsd:date">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Registreerimise kuupäev</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="kustutamise_kpv" type="xsd:date" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Kustutamise kuupäev</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="staatus" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Usaldushalduse staatus</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="staatus_tekstina" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Usaldushalduse staatus tekstina</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="riik" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Usaldushalduse riik</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="riik_tekstina" type="xsd:string">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Usaldushalduse riik tekstina</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="kasusaajate_arv_kokku" type="xsd:integer">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Kasusaajad arv kokku.</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="peidetud_kasusaajate_arv" type="xsd:integer">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Peidetud kasusaajate arv.</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="lahknevusteade_puudumisest" type="xsd:boolean">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Kas on esitatud lahknevusteade kasusaajate puudumisest.</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="isikud" type="ar:usaldushaldused_v1_isikud" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Seotud isikud.</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="usaldushaldused_v1_isikud">
        <xsd:annotation>
            <xsd:appinfo>
                <xrd:title>Seotud isikud</xrd:title>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="isik" maxOccurs="unbounded" minOccurs="0" type="ar:usaldushaldused_v1_isik">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Seotud isikud.</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="usaldushaldused_v1_isik">
        <xsd:annotation>
            <xsd:appinfo>
                <xrd:title>Seotud isik vastuses</xrd:title>
            </xsd:appinfo>
        </xsd:annotation>
            <xsd:sequence>
                <xsd:element name="roll" type="xsd:string" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <xrd:title>Isiku roll</xrd:title>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="roll_tekstina" type="xsd:string" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <xrd:title>Isiku roll</xrd:title>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="eesnimi" type="xsd:string" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <xrd:title>Eesnimi</xrd:title>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="nimi" type="xsd:string" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <xrd:title>Perekonnanimi</xrd:title>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="isikukood" type="xsd:string" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <xrd:title>Isikukood</xrd:title>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="valis_kood" type="xsd:string" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <xrd:title>Väliskood</xrd:title>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="valis_kood_riik" type="xsd:string" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <xrd:title>Väliskoodi riik</xrd:title>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="valis_kood_riik_tekstina" type="xsd:string" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <xrd:title>Väliskoodi riik tekstina</xrd:title>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="synniaeg" type="xsd:date" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <xrd:title>Sünniaeg</xrd:title>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="elukoht_riik" type="xsd:string" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <xrd:title>Elukoht: riik</xrd:title>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="elukoht_riik_tekstina" type="xsd:string" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <xrd:title>Elukoha riik tekstina</xrd:title>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="aadress_riik" type="xsd:string" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <xrd:title>Aadress: riik</xrd:title>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="aadress_riik_tekstina" type="xsd:string" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <xrd:title>Aadressi riik tekstina</xrd:title>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="kontrolli_teostamise_viis" type="xsd:string" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <xrd:title>Kontrolli teostamise viis</xrd:title>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="kontrolli_teostamise_viis_tekstina" type="xsd:string" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <xrd:title>Kontrolli teostamise viis tekstina</xrd:title>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="algus_kpv" type="xsd:date" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <xrd:title>Alguskuupäev</xrd:title>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="lopp_kpv" type="xsd:date" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <xrd:title>Lõppkuupäev</xrd:title>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="lahknevusteade_esitatud" type="xsd:boolean" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <xrd:title>Kas on esitatud lahknevusteade kasusaaja kohta.</xrd:title>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="usaldushaldused_v1_mps_koodid">
        <xsd:annotation>
            <xsd:appinfo>
                <xrd:title>Maaparandussüsteemi koodid</xrd:title>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="mps_kood" maxOccurs="unbounded" minOccurs="0" type="ar:usaldushaldused_v1_mps_kood">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Maaparandussüsteemi kood</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="usaldushaldused_v1_mps_kood">
        <xsd:annotation>
            <xsd:appinfo>
                <xrd:title>Kasusaaja vastuses</xrd:title>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="kirje_id" type="xsd:integer" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>ID</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="kaardi_piirkond" type="xsd:integer" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Kaardi piirkond</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="kaardi_nr" type="xsd:integer" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Kaardi number</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="kaardi_tyyp" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Kaardi tüüp</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="kande_nr" type="xsd:integer" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Kande number</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element minOccurs="0" name="sisu" type="xsd:string">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>MPS kood</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="algus_kpv" type="xsd:date" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Alguskuupäev</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="lopp_kpv" type="xsd:date" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
                        <xrd:title>Lõppkuupäev</xrd:title>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="usaldushaldused_v1">
        <xsd:sequence>
            <xsd:element name="keha" type="ar:usaldushaldused_v1_Query" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="usaldushaldused_v1Response">
        <xsd:sequence>
            <xsd:element name="paring" type="ar:usaldushaldused_v1_Query" />
            <xsd:element name="keha" type="ar:usaldushaldused_v1_Vastus" />
        </xsd:sequence>
    </xsd:complexType>

<!-- wrapper declarations -->
    <xsd:element name="usaldushaldused_v1" type="ar:usaldushaldused_v1"/>
    <xsd:element name="usaldushaldused_v1Response" type="ar:usaldushaldused_v1Response"/>
<!-- /wrapper declarations -->

</xsd:schema>
